# Generated by Django 5.2.1 on 2025-06-01 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servic', '0004_userrolechangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=10)),
                ('request_reason', models.TextField(help_text='Razón por la que desea convertirse en prestador')),
                ('admin_response', models.TextField(blank=True, help_text='Respuesta del administrador', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Prestador',
                'verbose_name_plural': 'Solicitudes de Prestadores',
                'ordering': ['-created_at'],
            },
        ),
    ]
